# Root directory for storing all artifacts
artifacts_root: artifacts

# Data ingestion process configurations
data_ingestion:
  root_dir: artifacts/data_ingestion  # Directory to store data ingestion outputs
  source_URL: "https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing"  # URL to download data
  local_data_file: artifacts/data_ingestion/data.zip  # Path to store the downloaded data file
  unzip_dir: artifacts/data_ingestion  # Directory where the data will be extracted

# Model preparation configurations
prepare_base_model:
  root_dir: artifacts/prepare_base_model  # Directory to store model preparation outputs
  base_model_path: artifacts/prepare_base_model/base_model.h5  # Path to the base model file
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5  # Path to the updated base model file

# Training process configurations
training:
  root_dir: artifacts/training  # Directory to store training outputs
  trained_model_path: artifacts/training/model.h5  # Path to save the trained model
